app = "audioverse-worker"

[build]
  dockerfile = "Dockerfile"

# Run the Celery worker as the main machine process
[processes]
  worker = "celery -A audioverse worker -l info"

[machines]
  auto_start = true
  auto_stop = false
  min_machines_running = 1

[env]
  ALLOWED_HOSTS = "audioverse-backend-serr.onrender.com"
  DATABASE_URL = "postgresql://audioverse_db_user:G8oFLDXMXruri8G1UXgOCtF9O6VJYJsL@dpg-d4d0bpfdiees73cahlm0-a.oregon-postgres.render.com/audioverse_db"
  DEBUG = "False"
  SECRET_KEY = "your-production-secret-key"
  CELERY_BROKER_URL="rediss://red-d4d0ceidbo4c73dhuoo0:rgxAb1YoSLZKQq8ZzVGyXn5qPxbOCfS6@oregon-keyvalue.render.com:6379/0"
  CELERY_RESULT_BACKEND="rediss://red-d4d0ceidbo4c73dhuoo0:rgxAb1YoSLZKQq8ZzVGyXn5qPxbOCfS6@oregon-keyvalue.render.com:6379/0"
  REDIS_URL="rediss://red-d4d0ceidbo4c73dhuoo0:rgxAb1YoSLZKQq8ZzVGyXn5qPxbOCfS6@oregon-keyvalue.render.com:6379"
