# Generated by Django 5.2.8 on 2025-11-25 09:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audiobooks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_generated', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recommendation_batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.FloatField(default=0.0, help_text='Recommendation confidence score')),
                ('reason', models.CharField(choices=[('genre', 'Based on your favorite genres'), ('author', 'Based on authors you like'), ('similar', 'Similar to books you enjoyed'), ('popular', 'Popular in your genres'), ('new', 'New releases you might like')], default='genre', max_length=20)),
                ('is_viewed', models.BooleanField(default=False)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('audiobook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audiobooks.audiobook')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recommendations',
                'ordering': ['-score', '-created_at'],
                'indexes': [models.Index(fields=['user', '-score'], name='recommendat_user_id_8236a6_idx'), models.Index(fields=['user', 'is_dismissed'], name='recommendat_user_id_dda46a_idx')],
                'unique_together': {('user', 'audiobook')},
            },
        ),
    ]
